# Form implementation generated from reading ui file 'aboutProgram.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(590, 430)
        Form.setMinimumSize(QtCore.QSize(590, 430))
        Form.setMaximumSize(QtCore.QSize(590, 430))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 235))
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.back_btn = QtWidgets.QPushButton(parent=Form)
        self.back_btn.setMinimumSize(QtCore.QSize(170, 40))
        self.back_btn.setObjectName("back_btn")
        self.verticalLayout.addWidget(self.back_btn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "О программе"))
        self.label.setText(_translate("Form", "О программе "))
        self.label_2.setText(_translate("Form", "eLibrary (Версия 1.0)"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"justify\">Данная программа предназначена для предоставления возможности скачать электронные книги с удалённого сервера через предоставляемый клиенту каталог.</p><p align=\"justify\">Для начала работы необходимо зарегистрироваться: придумать и запомнить имя логин и пароль, которые мы надёжно будем хранить в своей базе данных для ваших будущих сеансов.</p><p align=\"justify\">Чтобы скачать себе книгу, подберите интересующих авторов, жанры, дату издания и рейтинг под себя, воспользуйтесь поисковой строкой, а затем нажмите на &quot;Скачать книгу&quot; и выберите место на своём компьютере для ее загрузки.</p></body></html>"))
        self.back_btn.setText(_translate("Form", "Назад"))
