# Form implementation generated from reading ui file 'bookCardWidget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BookCardWidget(object):
    def setupUi(self, BookCardWidget):
        BookCardWidget.setObjectName("BookCardWidget")
        BookCardWidget.resize(748, 249)
        self.horizontalLayout = QtWidgets.QHBoxLayout(BookCardWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.picture_label = QtWidgets.QLabel(parent=BookCardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture_label.sizePolicy().hasHeightForWidth())
        self.picture_label.setSizePolicy(sizePolicy)
        self.picture_label.setMinimumSize(QtCore.QSize(188, 0))
        self.picture_label.setMaximumSize(QtCore.QSize(231, 380))
        self.picture_label.setScaledContents(True)
        self.picture_label.setObjectName("picture_label")
        self.horizontalLayout.addWidget(self.picture_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(parent=BookCardWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.author_label = QtWidgets.QLabel(parent=BookCardWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.author_label.setFont(font)
        self.author_label.setObjectName("author_label")
        self.verticalLayout.addWidget(self.author_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.summary_label = QtWidgets.QLabel(parent=BookCardWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.summary_label.setFont(font)
        self.summary_label.setWordWrap(True)
        self.summary_label.setObjectName("summary_label")
        self.verticalLayout.addWidget(self.summary_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_label = QtWidgets.QLabel(parent=BookCardWidget)
        self.date_label.setObjectName("date_label")
        self.horizontalLayout_2.addWidget(self.date_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.download_label = QtWidgets.QLabel(parent=BookCardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_label.sizePolicy().hasHeightForWidth())
        self.download_label.setSizePolicy(sizePolicy)
        self.download_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.download_label.setObjectName("download_label")
        self.horizontalLayout_2.addWidget(self.download_label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(BookCardWidget)
        QtCore.QMetaObject.connectSlotsByName(BookCardWidget)

    def retranslateUi(self, BookCardWidget):
        _translate = QtCore.QCoreApplication.translate
        BookCardWidget.setWindowTitle(_translate("BookCardWidget", "Form"))
        self.picture_label.setText(_translate("BookCardWidget", "Пикча"))
        self.name_label.setText(_translate("BookCardWidget", "Название"))
        self.author_label.setText(_translate("BookCardWidget", "Автор"))
        self.summary_label.setText(_translate("BookCardWidget", "Описание"))
        self.date_label.setText(_translate("BookCardWidget", "Дата издания"))
        self.download_label.setText(_translate("BookCardWidget", "Скачать книгу"))
